### PR TITLE
fix: regenerate all protos under new namespace

### PR DESCRIPTION
**Pull request by codyoss**
This should be wire compat as field numbers did not change and package is not apart of the serialization. I appened `.v2` to each proto package so that these protos can register distinctly from the protos that were copied from the v1 library. This removes runtime errors due to double registration of the same messages. Note: I did have to specially regenerate taskqueue with a special built version of protoc-gen-go in order to generate some proto1 legacy message type that is referenced.

Fixes: #311
Fixes: https://github.com/googleapis/google-cloud-go/issues/7760

### CODE REVIEW

**Comment by jinglundong** [comment]
Regarding the CI test failures, it seems like we need to upgrade the python interpreter to python 3. https://github.com/search?q=repo%3Agolang%2Fappengine%20python&type=code. I think it's caused by a recent change in gcloud.

**Comment by jinglundong** [comment]
I'm trying to fix the ci tests.

**Comment by codyoss** [comment]
@jinglundong Any progress to share. This fix is needed to help people upgrade their dependencies.

**Comment by jinglundong** [comment]
We will work on the python2-> 3 migration for the CI/CD of this repo.

**Comment by jinglundong** [comment]
Giving a shot at https://github.com/golang/appengine/pull/315.

**Comment by jinglundong** [comment]
I believe the CI tests are fixed after https://github.com/golang/appengine/pull/315 and https://github.com/golang/appengine/pull/316.

**Pull request merged**
