### PR TITLE
remote_api: don't check auth for dev_appserver

### PR DESCRIPTION
**Pull request by broady**

### CODE REVIEW

**Comment by broady** [comment]
(mostly a check for the CLA bot, this commit needs a better description)

**Comment by broady** [comment]
@googlebot check me!

**Comment by adamtanner** [comment]
Is this just a test for CLA or should we actually merge this? :)

**Comment by broady** [comment]
I think we should merge this, but I'm not completely sure.

I needed this while using `appcfg.py {download,upload}_data`, but that's being superseded by gcloud without any equivalent(?)

**Pull request merged**
