### PR TITLE
Added read-only transaction support, supply previous transaction id.

### PR DESCRIPTION
**Pull request by danchia**
I didn't find any E2E tests - do they exist somewhere? Was trying to find the right process to test these changes.

### CODE REVIEW

**Comment by danchia** [comment]
@jba

**Comment by zombiezen** [comment]
LGTM. No automated tests.  Since this is a go-gettable package, you can spin up an App Engine Standard app and check that it does the right thing on datastore.

**Comment by danchia** [comment]
A small bugfix, but otherwise I think this is good to go. I tested this by deploying to a GAE project.

Would appreciate if you will squash and merge this, thanks!

**Comment by sbuss** [comment]
@jba Can you take another look? Changes were made after your last review.

**Pull request merged**
