### PR TITLE
LICENSE: Fix license boilerplate

### PR DESCRIPTION
**Pull request by kevinburke**
The bottom of the LICENSE field is the part that you are supposed to copy when
you include this code in other projects. It would be good for it to say
"Google, Inc" instead of "[copyright year] [copyright holder]."

### CODE REVIEW

**Comment by kevinburke** [comment]
I've signed the Google CLA, if it matters, it's also simple enough for you to make this change.

**Comment by broady** [comment]
Actually, you're not supposed to modify the LICENSE file in this way. Read the section above:
```

   APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.
```

**Comment by kevinburke** [comment]
Interesting, you may want to coordinate with the google-cloud-go owners in that case. https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/LICENSE

**Comment by broady** [comment]
@kevinburke I don't think there's any harm in it, but there's no benefit, either (tell me if your lawyer says otherwise!)

**Pull request closed without merging**
