### PR TITLE
Let users specify unique function keys using delay.MustRegister

### PR DESCRIPTION
**Pull request by KaylaNguyen**

### CODE REVIEW

**Comment by zevdg** [comment]
I'm a little confused.  At a glance, this looks like the same exact change as #261 just on the master branch instead of qa and squashed to 1 commit.  Is that right?  If so, this SGTM.  We made this change in a totally backwards compatible way so backporting it to master makes total sense.

Since we already reviewed the code in #261, it seems like the approver for this CL should be verifing that you've backported the fix from qa to master correctly. If your team has a process for this, I don't know what it is, so I can't verify that you've follow it correctly. If they don't have a process and you're flying by the seat of your pants, that's ok for now, but you should document how you did this one as a baseline and I can at least review that process.

**Comment by KaylaNguyen** [comment]
Yes, this commit is an exact replica of #261 but to `master` branch. We don't have a process for this so I'm just porting this change manually.

**Comment by zevdg** [comment]
Did you run some git commands to create this commit?  I'd feel much better about approving this if it was created by a `git merge --squash`. If not, could you try recreating this change using `git merge --squash`?

**Comment by KaylaNguyen** [comment]
TIL, thanks!
I did
→ git checkout master
→ git merge --squash delaypkg
→ git commit ....
→ git checkout delaypkg-master
→ git merge qa-upstream

A bit roundabout but I think that works.

**Review by zevdg — APPROVED** [review]

**Pull request merged**
